[2023-11-16T08:54:20.695+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: change_working_dir_example.change_working_directory_task manual__2023-11-16T08:54:19.020473+00:00 [queued]>
[2023-11-16T08:54:20.707+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: change_working_dir_example.change_working_directory_task manual__2023-11-16T08:54:19.020473+00:00 [queued]>
[2023-11-16T08:54:20.707+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-16T08:54:20.725+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): change_working_directory_task> on 2023-11-16 08:54:19.020473+00:00
[2023-11-16T08:54:20.731+0000] {standard_task_runner.py:57} INFO - Started process 1360 to run task
[2023-11-16T08:54:20.748+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'change_working_dir_example', 'change_working_directory_task', 'manual__2023-11-16T08:54:19.020473+00:00', '--job-id', '770', '--raw', '--subdir', 'DAGS_FOLDER/working-directory.py', '--cfg-path', '/tmp/tmp95x3lt4m']
[2023-11-16T08:54:20.756+0000] {standard_task_runner.py:85} INFO - Job 770: Subtask change_working_directory_task
[2023-11-16T08:54:20.871+0000] {task_command.py:416} INFO - Running <TaskInstance: change_working_dir_example.change_working_directory_task manual__2023-11-16T08:54:19.020473+00:00 [running]> on host 4c85f18ab3d7
[2023-11-16T08:54:21.104+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='nguyenthung' AIRFLOW_CTX_DAG_ID='change_working_dir_example' AIRFLOW_CTX_TASK_ID='change_working_directory_task' AIRFLOW_CTX_EXECUTION_DATE='2023-11-16T08:54:19.020473+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-16T08:54:19.020473+00:00'
[2023-11-16T08:54:21.106+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/working-directory.py", line 10, in change_working_directory
    os.chdir(new_directory)
FileNotFoundError: [Errno 2] No such file or directory: '/home/nguyenthung/Desktop/Docker-Airflow'
[2023-11-16T08:54:21.128+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=change_working_dir_example, task_id=change_working_directory_task, execution_date=20231116T085419, start_date=20231116T085420, end_date=20231116T085421
[2023-11-16T08:54:21.163+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 770 for task change_working_directory_task ([Errno 2] No such file or directory: '/home/nguyenthung/Desktop/Docker-Airflow'; 1360)
[2023-11-16T08:54:21.192+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-16T08:54:21.230+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
