[2023-11-12T13:25:05.008+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: miai_dag.crawl_data manual__2023-11-12T13:19:42.281381+00:00 [queued]>
[2023-11-12T13:25:05.019+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: miai_dag.crawl_data manual__2023-11-12T13:19:42.281381+00:00 [queued]>
[2023-11-12T13:25:05.019+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2023-11-12T13:25:05.036+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): crawl_data> on 2023-11-12 13:19:42.281381+00:00
[2023-11-12T13:25:05.047+0000] {standard_task_runner.py:57} INFO - Started process 37994 to run task
[2023-11-12T13:25:05.054+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'miai_dag', 'crawl_data', 'manual__2023-11-12T13:19:42.281381+00:00', '--job-id', '136', '--raw', '--subdir', 'DAGS_FOLDER/dag-lstm.py', '--cfg-path', '/tmp/tmpirxsul42']
[2023-11-12T13:25:05.058+0000] {standard_task_runner.py:85} INFO - Job 136: Subtask crawl_data
[2023-11-12T13:25:05.139+0000] {task_command.py:416} INFO - Running <TaskInstance: miai_dag.crawl_data manual__2023-11-12T13:19:42.281381+00:00 [running]> on host 502cd78af35e
[2023-11-12T13:25:05.253+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='nguyenthung' AIRFLOW_CTX_DAG_ID='miai_dag' AIRFLOW_CTX_TASK_ID='crawl_data' AIRFLOW_CTX_EXECUTION_DATE='2023-11-12T13:19:42.281381+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-12T13:19:42.281381+00:00'
[2023-11-12T13:25:05.259+0000] {logging_mixin.py:151} INFO - https://finfo-api.vndirect.com.vn/v4/stock_prices?sort=date&q=code:DIG~date:gte:2000-01-01~date:lte:2023-11-12&size=9990&page=1
[2023-11-12T13:25:07.713+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag-lstm.py", line 50, in craw_stock_price
    stock_price_df = stock_price_df.append(stock, ignore_index=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 5989, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'append'
[2023-11-12T13:25:07.727+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=miai_dag, task_id=crawl_data, execution_date=20231112T131942, start_date=20231112T132505, end_date=20231112T132507
[2023-11-12T13:25:07.741+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 136 for task crawl_data ('DataFrame' object has no attribute 'append'; 37994)
[2023-11-12T13:25:07.771+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-12T13:25:07.794+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
