[2023-11-16T14:33:04.314+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: miai_dag.load_phase manual__2023-11-16T14:27:37.465085+00:00 [queued]>
[2023-11-16T14:33:04.324+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: miai_dag.load_phase manual__2023-11-16T14:27:37.465085+00:00 [queued]>
[2023-11-16T14:33:04.325+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2023-11-16T14:33:04.337+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load_phase> on 2023-11-16 14:27:37.465085+00:00
[2023-11-16T14:33:04.347+0000] {standard_task_runner.py:57} INFO - Started process 37352 to run task
[2023-11-16T14:33:04.352+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'miai_dag', 'load_phase', 'manual__2023-11-16T14:27:37.465085+00:00', '--job-id', '838', '--raw', '--subdir', 'DAGS_FOLDER/dag-lstm.py', '--cfg-path', '/tmp/tmpvxzj4gqd']
[2023-11-16T14:33:04.356+0000] {standard_task_runner.py:85} INFO - Job 838: Subtask load_phase
[2023-11-16T14:33:04.408+0000] {task_command.py:416} INFO - Running <TaskInstance: miai_dag.load_phase manual__2023-11-16T14:27:37.465085+00:00 [running]> on host 4c85f18ab3d7
[2023-11-16T14:33:04.503+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='nguyenthung' AIRFLOW_CTX_DAG_ID='miai_dag' AIRFLOW_CTX_TASK_ID='load_phase' AIRFLOW_CTX_EXECUTION_DATE='2023-11-16T14:27:37.465085+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-16T14:27:37.465085+00:00'
[2023-11-16T14:33:04.510+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag-lstm.py", line 135, in load
    cur.execute(
TypeError: not all arguments converted during string formatting
[2023-11-16T14:33:04.519+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=miai_dag, task_id=load_phase, execution_date=20231116T142737, start_date=20231116T143304, end_date=20231116T143304
[2023-11-16T14:33:04.530+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 838 for task load_phase (not all arguments converted during string formatting; 37352)
[2023-11-16T14:33:04.566+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-16T14:33:04.584+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
