[2023-11-17T05:49:54.654+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_procesing.load_phase manual__2023-11-17T05:44:34.654831+00:00 [queued]>
[2023-11-17T05:49:54.665+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_procesing.load_phase manual__2023-11-17T05:44:34.654831+00:00 [queued]>
[2023-11-17T05:49:54.665+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2023-11-17T05:49:54.679+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load_phase> on 2023-11-17 05:44:34.654831+00:00
[2023-11-17T05:49:54.690+0000] {standard_task_runner.py:57} INFO - Started process 35831 to run task
[2023-11-17T05:49:54.695+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'etl_procesing', 'load_phase', 'manual__2023-11-17T05:44:34.654831+00:00', '--job-id', '888', '--raw', '--subdir', 'DAGS_FOLDER/dag-lstm.py', '--cfg-path', '/tmp/tmp81li3zns']
[2023-11-17T05:49:54.700+0000] {standard_task_runner.py:85} INFO - Job 888: Subtask load_phase
[2023-11-17T05:49:54.788+0000] {task_command.py:416} INFO - Running <TaskInstance: etl_procesing.load_phase manual__2023-11-17T05:44:34.654831+00:00 [running]> on host 4c85f18ab3d7
[2023-11-17T05:49:54.888+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='nguyenthung' AIRFLOW_CTX_DAG_ID='etl_procesing' AIRFLOW_CTX_TASK_ID='load_phase' AIRFLOW_CTX_EXECUTION_DATE='2023-11-17T05:44:34.654831+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-17T05:44:34.654831+00:00'
[2023-11-17T05:49:54.894+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag-lstm.py", line 139, in load
    cur.execute(
TypeError: not all arguments converted during string formatting
[2023-11-17T05:49:54.905+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=etl_procesing, task_id=load_phase, execution_date=20231117T054434, start_date=20231117T054954, end_date=20231117T054954
[2023-11-17T05:49:54.921+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 888 for task load_phase (not all arguments converted during string formatting; 35831)
[2023-11-17T05:49:54.949+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-17T05:49:54.987+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
